backend:
  name: git-gateway
  branch: main
collections:
  - name: "noticias"
    label: "Noticias"
    folder: "src/content/noticias"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }

  - name: "arteycultura"
    label: "Arte y Cultura"
    folder: "src/content/arteycultura"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }

  - name: "agroecologia"
    label: "Agroecología"
    folder: "src/content/agroecologia"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "/assets/images"