backend:
  name: git-gateway
  branch: main
collections:
  - name: "blog"
    label: "Artículos"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "pubDate", widget: "datetime" }
      - { label: "Descripción", name: "description", widget: "string" }  # Added description
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Texto", name: "body", widget: "markdown", output: true}

media_folder: "src/assets/images"  # Location where files will be stored in the repo
public_folder: "/assets/images"  # Public folder for media assets

media_library:
  name: cloudinary
  config:
    cloud_name: furiosasresistencias
    api_key: 152266985847232